site_name: Docker Bitcoin Core
site_url: https://BarneyBuffet.github.io/docker-bitcoin-core/
theme:
  name: material
nav:
    - "Home": index.md
    - "Why": why.md
    - "Environmental Variables": environmental.md
    - "Tor": tor.md